configure: clean up

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,12 +2,41 @@
 
 set -e
 
-SRC_DIR="$(pwd)"
-BUILD_DIR="$SRC_DIR"  # Default to source directory
+PROJECT_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
+
+generate_test_setup_sh() {
+  build_dir="$1"
+
+  setup_sh="${PROJECT_ROOT}/test/setup.sh"
+  :>"$setup_sh"
+
+  cat >"$setup_sh" <<EOF
+# This file has been generated by the configure script
+alias atp="${build_dir}/bin/main.byte"
+EOF
+}
+
+setup_out_of_tree_build() {
+  build_dir="$1"
+
+  mkdir -p "$build_dir"
+
+  for dir in bin lib test; do
+    cp -asf "${PROJECT_ROOT}/${dir}" "${build_dir}/"
+  done
+
+  ln -sf "${PROJECT_ROOT}/GNUmakefile" "${build_dir}/GNUmakefile"
+
+  find "$build_dir" -name .merlin -delete
+}
 
 check_python_module() {
-  printf "checking for Python module %s... " "$1"
-  python3 -c "import $1" >/dev/null 2>&1
+  module="$1"
+
+  printf "checking for Python module %s... " "$module"
+
+  python3 -c "import $module" >/dev/null 2>&1
+
   if [ $? -eq 0 ]; then
     printf "yes\n"
     return 0
@@ -17,20 +46,10 @@ check_python_module() {
   fi
 }
 
-setup_out_of_tree_build() {
-  mkdir -p "$BUILD_DIR"
-
-  for dir in bin lib test; do
-    cp -asf "${SRC_DIR}/${dir}" "${BUILD_DIR}/"
-  done
-
-  ln -sf "${SRC_DIR}/GNUmakefile" "${BUILD_DIR}/GNUmakefile"
-
-  find "$BUILD_DIR" -name .merlin -delete
-}
-
 generate_config_mk() {
-  config_mk="${BUILD_DIR}/config.mk"
+  build_dir="$1"
+
+  config_mk="${build_dir}/config.mk"
   :>"$config_mk"
 
   if check_python_module "cram"; then
@@ -39,10 +58,12 @@ generate_config_mk() {
 }
 
 generate_dot_merlin() {
-  dot_merlin="${SRC_DIR}/.merlin"
+  build_dir="$1"
+
+  dot_merlin="${PROJECT_ROOT}/.merlin"
   :>"$dot_merlin"
 
-  build_path=$(realpath --relative-to="$SRC_DIR" "$BUILD_DIR")
+  build_path=$(realpath --relative-to="$PROJECT_ROOT" "$build_dir")
 
   cat >"$dot_merlin" <<EOF
 S bin
@@ -56,18 +77,10 @@ B ${build_path}/test
 EOF
 }
 
-generate_test_setup_sh() {
-  setup_sh="${SRC_DIR}/test/setup.sh"
-  :>"$setup_sh"
-
-  cat >"$setup_sh" <<EOF
-# This file has been generated by the configure script
-alias atp="${BUILD_DIR}/bin/main.byte"
-EOF
-}
-
 generate_dot_ocamlinit() {
-  dot_ocamlinit="${SRC_DIR}/.ocamlinit"
+  build_dir="$1"
+
+  dot_ocamlinit="${PROJECT_ROOT}/.ocamlinit"
   :>"$dot_ocamlinit"
 
   cat >"$dot_ocamlinit" <<EOF
@@ -81,9 +94,9 @@ let () = try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH") with Not_f
 
 #require "zarith"
 
-#directory "${BUILD_DIR}/lib/intro"
+#directory "${build_dir}/lib/intro"
 
-#directory "${BUILD_DIR}/lib/prop_logic"
+#directory "${build_dir}/lib/prop_logic"
 
 #load "intro.cma"
 
@@ -97,50 +110,56 @@ usage() {
   printf "  -h            Display this help message\n"
 }
 
-# Parse command-line arguments
-while [ $# -gt 0 ]; do
-  case "$1" in
-    -d)
-      if [ -n "$2" ]; then
-        BUILD_DIR=$(realpath "$2")
-        shift 2
-      else
-        printf "Error: -d requires a directory argument.\n"
+main() {
+  arg_build_dir="$PROJECT_ROOT" # Default to project root
+
+  # Parse command-line arguments
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -d)
+        if [ -n "$2" ]; then
+          arg_build_dir=$(realpath "$2")
+          shift 2
+        else
+          printf "Error: -d requires a directory argument.\n"
+          exit 1
+        fi
+        ;;
+      -h)
+        usage
+        exit 0
+        ;;
+      *)
+        printf "Unknown option: $1\n"
+        usage
         exit 1
-      fi
-      ;;
-    -h)
-      usage
-      exit 0
-      ;;
-    *)
-      printf "Unknown option: $1\n"
-      usage
-      exit 1
-      ;;
-  esac
-done
+        ;;
+    esac
+  done
 
-# Generate test/setup.sh
-generate_test_setup_sh
+  # Generate test/setup.sh
+  generate_test_setup_sh "$arg_build_dir"
 
-# If BUILD_DIR is different from SRC_DIR, set up out-of-tree build
-printf "checking for out of tree build... "
-if [ "$BUILD_DIR" != "$SRC_DIR" ]; then
-  printf "yes\n"
-  setup_out_of_tree_build
-else
-  printf "no\n"
-fi
+  # If arg_build_dir is different from PROJECT_ROOT, set up out-of-tree build
+  printf "checking for out of tree build... "
+  if [ "$arg_build_dir" != "$PROJECT_ROOT" ]; then
+    printf "yes\n"
+    setup_out_of_tree_build "$arg_build_dir"
+  else
+    printf "no\n"
+  fi
 
-# Generate config.mk
-generate_config_mk
+  # Generate config.mk
+  generate_config_mk "$arg_build_dir"
 
-# Generate .merlin
-generate_dot_merlin
+  # Generate .merlin
+  generate_dot_merlin "$arg_build_dir"
 
-# Generate .ocamlinit
-generate_dot_ocamlinit
+  # Generate .ocamlinit
+  generate_dot_ocamlinit "$arg_build_dir"
 
-printf "Build directory: %s\n" "$BUILD_DIR"
-printf "OK\n"
+  printf "Build directory: %s\n" "$arg_build_dir"
+  printf "OK\n"
+}
+
+main "$@"
